### PR TITLE
Add option to exclude entities and use wild cards / regular expressions

### PR DESCRIPTION
**Pull request by FH-Inway**
See #8

### CODE REVIEW

**Comment by FH-Inway** [comment]
@shashisadasivan Had to do some branch switching to work on another feature. If you are still interested in this one, let me know if I should make any changes.

**Comment by shashisadasivan** [comment]
Thanks @FH-Inway , although would it be easier to have a swith to either include or exclude, instead of both ? Which would take preference ?
I have merged this curently as its been working for you and i havent used this for ages to be honest

**Comment by FH-Inway** [comment]
@shashisadasivan Thanks for the merge. I can add a switch, although I intentionally kept the option that both can be used. The list of entities to keep takes preference. From the result, the entities to exclude are then removed.
This I believe makes sense since now wildcards can be used. So for example, I could specify that I want to keep all entities that have "sales" in their name. But then I want to exclude some of those entities. You could achieve this also with just the entities to keep parameter using a regular expression. But it is much easier with the entities to exclude parameter.

If this works for you, I can provide some additional hints in the help texts of the parameters to indicate which takes preference.

**Comment by shashisadasivan** [comment]
> @shashisadasivan Thanks for the merge. I can add a switch, although I intentionally kept the option that both can be used. The list of entities to keep takes preference. From the result, the entities to exclude are then removed. This I believe makes sense since now wildcards can be used. So for example, I could specify that I want to keep all entities that have "sales" in their name. But then I want to exclude some of those entities. You could achieve this also with just the entities to keep parameter using a regular expression. But it is much easier with the entities to exclude parameter.
> 
> If this works for you, I can provide some additional hints in the help texts of the parameters to indicate which takes preference.

That sounds good. Are you able to update the readme on how to use this since the switches changes?

**Comment by FH-Inway** [comment]
👍 Will do.

**Pull request merged**
